name: jaffle_shop
description: ''
version: '1'
author: null
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/xx:
    name: xx
    description: ''
    fabricUID: 247
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: prophecy_internal_jobs
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2024-03-11 09:41:54'
    author: sony@prophecy.io
  jobs/airf:
    name: airf
    description: ''
    fabricUID: 2526
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: true
    createdAt: '2024-03-22 10:29:54'
    author: sony@prophecy.io
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-02-29 06:15:50'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/stg_orders:
    name: stg_orders
    schema:
      providerType: Snowflake
      fields:
      - name: ORDER_ID
        dataType:
          type: Number
      - name: ORDER_DATE
        dataType:
          type: Date
      - name: STATUS
        dataType:
          type: String
    description: null
    author: sony@prophecy.io
    files:
    - models/staging/stg_orders.sql
    - .prophecy/ide/models/stg_orders.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2024-02-29 06:15:50'
  .prophecy/metadata/sqlmodels/orders:
    name: orders
    schema:
      providerType: Snowflake
      fields:
      - name: ORDER_ID
        dataType:
          type: Number
      - name: ORDER_DATE
        dataType:
          type: Date
      - name: STATUS
        dataType:
          type: String
      - name: CREDIT_CARD_AMOUNT
        dataType:
          type: Number
      - name: COUPON_AMOUNT
        dataType:
          type: Number
      - name: BANK_TRANSFER_AMOUNT
        dataType:
          type: Number
      - name: GIFT_CARD_AMOUNT
        dataType:
          type: Number
      - name: AMOUNT
        dataType:
          type: Number
    description: This table has basic information about orders, as well as some derived
      facts based on payments
    author: sony@prophecy.io
    files:
    - models/orders.sql
    - .prophecy/ide/models/orders.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2024-02-29 06:15:50'
  .prophecy/metadata/sqlmodels/customers:
    name: customers
    schema:
      providerType: Snowflake
      fields:
      - name: ID
        dataType:
          type: Number
      - name: FIRST_NAME
        dataType:
          type: String
    description: This table has basic information about a customer, as well as some
      derived facts based on a customer's orders
    author: sony@prophecy.io
    files:
    - models/customers.sql
    - .prophecy/ide/models/customers.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2024-02-29 06:15:50'
  .prophecy/metadata/sqlmodels/stg_payments:
    name: stg_payments
    schema:
      providerType: Snowflake
      fields:
      - name: PAYMENT_ID
        dataType:
          type: Number
      - name: ORDER_ID
        dataType:
          type: Number
      - name: PAYMENT_METHOD
        dataType:
          type: String
      - name: AMOUNT
        dataType:
          type: Number
    description: null
    author: sony@prophecy.io
    files:
    - models/staging/stg_payments.sql
    - .prophecy/ide/models/stg_payments.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2024-02-29 06:15:50'
  .prophecy/metadata/sqlmodels/stg_customers:
    name: stg_customers
    schema:
      providerType: Snowflake
      fields:
      - name: ID
        dataType:
          type: Number
      - name: FIRST_NAME
        dataType:
          type: String
    description: null
    author: sony@prophecy.io
    files:
    - models/staging/stg_customers.sql
    - .prophecy/ide/models/stg_customers.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2024-02-29 06:15:50'
sqlMacros: {}
sqlSeeds:
  .prophecy/metadata/sqlseeds/raw_customers:
    name: raw_customers
    schema:
      providerType: Snowflake
      fields:
      - name: id
        dataType:
          type: Number
      - name: first_name_looooonggggggggggggg
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: sony@prophecy.io
    files:
    - seeds/raw_customers.csv
    createdAt: '2024-02-29 06:15:50'
  .prophecy/metadata/sqlseeds/raw_orders:
    name: raw_orders
    schema:
      providerType: Snowflake
      fields:
      - name: id
        dataType:
          type: Number
      - name: user_id_very_looooonggggggggggggggggg
        dataType:
          type: Number
      - name: order_date
        dataType:
          type: Date
      - name: status
        dataType:
          type: String
    description: null
    author: sony@prophecy.io
    files:
    - seeds/raw_orders.csv
    createdAt: '2024-02-29 06:15:50'
  .prophecy/metadata/sqlseeds/raw_payments:
    name: raw_payments
    schema:
      providerType: Snowflake
      fields:
      - name: id
        dataType:
          type: Number
      - name: order_id
        dataType:
          type: Number
      - name: payment_method
        dataType:
          type: String
      - name: amount
        dataType:
          type: Number
    description: null
    author: sony@prophecy.io
    files:
    - seeds/raw_payments.csv
    createdAt: '2024-02-29 06:15:50'
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: sony@prophecy.io
  createdAt: '2024-02-29 06:15:50'
dependencies: '[]'
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
